Dev 서지원
junheui27/Creativity_New pull request #25
Opened 2022-04-18 11:00 UTC by jw451

출력 정렬기능 구현 및 TC 추가했습니다.

2022-04-18 11:50 UTC, WhiteLeeDev requested changes
Print Option에 대한 추상화가 잘 되어 있어 option별로 변경관리가 용이할 것으로 보입니다! Comparable도 이해하기 쉽게 간단하게 적용해 주셨네요 :) 출력부분은 요구사항과 맞지 않는 부분이 있는 듯 하여 변경을 부탁드립니다 👍

2022-04-18 11:50 UTC, WhiteLeeDev commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +        for(Employee employee:tempList){
프린트를 위한 카운트를 세지말고 아래처럼 컬렉션의 갯수를 제한해서 쓰는게 더 깔끔하지 않을까 싶습니다  :)
```
List<Integer> contestWinners = contestents
            .stream()
            .limit(5)
            .collect(Collectors.toList());
```
reference: https://www.leveluplunch.com/java/examples/limit-or-take-first-elements-from-list/

2022-04-18 11:50 UTC, WhiteLeeDev commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +                    +employee.getEmployeeNum().substring(1)+","
employeeNum이 중복출력 되고 있는 것처럼 보입니다

2022-04-18 11:50 UTC, WhiteLeeDev commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +        Collections.sort(tempList);
Collections의 sort면.. 어떤 sort 방식을 사용하나요?

2022-04-18 11:50 UTC, WhiteLeeDev commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +            Employee copied=employee.Copy();
정렬할 대상이 많을 때, 그만큼의 객체의 모든 필드를 전부 copy하는건 좀 부담이 될듯 합니다
아래처럼 Employee를 필드로 가지는 정렬용 클래스를 쓰는게 어떨까요?

```
public class TempEmployee {
 private String tempEmployeeNum;
 private Employee originalEmployee;

 public TempEmployee(Employee employee){
     this.originalEmployee = employee;
     this.tempEmployeeNum = 정렬을 위한 사번 변환로직 추가
 }

//field별 get 함수 추가
 public String getName(){
    return  originalEmployee.getName();
}
}
```
이렇게 하고 comparable도 이 클래스에 두면 기준 모델인 Employee도 변경되지 않아서 장점이 잇을 것 같습니다.
상속도 생각해 봤는데.. 기존 객체를 부모로 가지도록 할 수가 없는듯 해서 안 될거같네요

2022-04-18 13:41 UTC, jw451 commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +            Employee copied=employee.Copy();
좋은 생각입니다. 성능을 위한 리팩토링을 생각하고있었는데, 좋은 아이디어 감사합니다:)

2022-04-18 13:50 UTC, jw451 commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +        Collections.sort(tempList);
https://codingnojam.tistory.com/38
timesort를 사용하는군요 보통 O(NlogN)의 시간복잡도를 가지는것같습니다.

2022-04-18 14:02 UTC, jw451 commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +                    +employee.getEmployeeNum().substring(1)+","
아.. 이런 네 수정했습니다. 감사합니다.

2022-04-18 14:25 UTC, jw451 commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +        for(Employee employee:tempList){
네 안그래도 좀 깔끔하지못해서 고민이었는데요.  감사합니다.

2022-04-19 00:01 UTC, smilesw6448 approved these changes

2022-04-19 00:01 UTC, smilesw6448 commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +        List<TempEmployee> limitList=tempList.stream().limit(5).collect(Collectors.toList());
수고많으셨습니다. 주석은 제거해주셔도 될거같습니다.

2022-04-19 00:05 UTC, WhiteLeeDev approved these changes
의견 반영 감사합니다! 다음에 DetailPrint 클래스 print 함수 내부의 각 동작을 함수로 명명해 주면 가독성이 향상될 것 같습니다. 주석도 제거할 수 있을듯 하고요 :)

2022-04-19 00:05 UTC, WhiteLeeDev commented on src/main/java/printer/DetailPrint/DetailPrint.java
> +        Collections.sort(tempList);
정렬을 잘 몰라서요... TimSort 라는게 있는걸 배웠네요ㅎㅎ 레퍼런스 감사합니다!!

2022-04-19 00:36 UTC, bw2218 approved these changes

2022-04-19 00:50 UTC, junheui27 approved these changes

2022-04-19 00:54 UTC, merged